// Generated by https://quicktype.io

export interface NewsResponse {
    status:       string;
    totalResults: number;
    articles:     Article[];
}

export interface Article {
    source:      Source;
    author?:     string;
    title:       string;
    description?:string;
    url:         string;
    urlToImage?: string;
    publishedAt: Date;
    content?:    string;
}

export interface Source {
    id?:  string;
    name: string;
}


// Generated by https://quicktype.io

export interface PanoramaResponse {
    page:          number;
    results:       Result[];
    total_pages:   number;
    total_results: string;
}

export interface Result {
    id:          number;
    datePublish: string;
    modified:    string;
    category:    string;
    tags:        string;
    infantil:    boolean;
    title:       string;
    description: string;
    image:       string;
    adress:      Adress;
    date:        DateClass;
    price:       Price;
    link:        string;
}

export interface Adress {
    calle:      string;
    referencia: string;
    comuna:     string;
    region:     Region;
}

export enum Region {
    RegiónMetropolitana = "Región Metropolitana",
}

export interface DateClass {
    fecha_inicio:  string;
    fecha_termino: string;
    dias_semana:   DiasSemana;
    hora_inicio:   string;
    hora_termino:  string;
}

export interface DiasSemana {
    lunes:     boolean;
    martes:    boolean;
    miercoles: boolean;
    jueves:    boolean;
    viernes:   boolean;
    sabado:    boolean;
    domingo:   boolean;
}

export interface Price {
    valor:       string;
    propinas:    boolean;
    valor_desde: boolean;
}



// Generated by https://quicktype.io

export interface PanoramaCategories {
    id:          number;
    count:       number;
    description: string;
    link:        string;
    name:        string;
    slug:        string;
    taxonomy:    Taxonomy;
    parent:      number;
    meta:        any[];
    _links:      Links;
}

export interface Links {
    self:           About[];
    collection:     About[];
    about:          About[];
    "wp:post_type": About[];
    curies:         Cury[];
}

export interface About {
    href: string;
}

export interface Cury {
    name:      Name;
    href:      Href;
    templated: boolean;
}

export enum Href {
    HTTPSAPIWOrgRel = "https://api.w.org/{rel}",
}

export enum Name {
    Wp = "wp",
}

export enum Taxonomy {
    Category = "category",
}


